on:
  workflow_dispatch:

jobs:
  download-from-fandom:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ 'windows-latest' ]

    steps:
    - uses: actions/checkout@v1

    - name: git checkout
      run: git checkout main      

    - name: Download from yuque
      run: python main.py
    
    - name: tree
      run: tree
    
    - name: git config
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
    
    - name: git add
      run: git add ${{ github.workspace }}\source\gensinimpact_pages_current.xml.7z
    
    - name: git commit
      run: git commit -m "update source file"
        
    - name: git push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
