on:
  workflow_dispatch:

jobs:
  download-from-yuque:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ 'windows-latest' ]

    steps:
    - uses: actions/checkout@v1

    - name: git checkout
      run: git checkout main
    
    - name: install python dependencies
      run: pip install requests win_unicode_console
      
    - name: Download from yuque
      shell: cmd
      run: |
        chcp 65001
        python main.py
    
    - name: tree
      run: tree
    
    - name: git config
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
    
    - name: git add
      run: git add .
    
    - name: git commit
      run: git commit -m "update source file"
        
    - name: git push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
